name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    # Prevents changesets action from creating a PR on forks
    if: github.repository == 'adyen/adyen-web'
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.15

      - name: Install Dependencies
        run: yarn

      - name: Create Release Pull Request
        uses: changesets/action@v1
        id: create_release_pr
        with:
          version: yarn run version
          commit: '[ci] release ${{ github.ref_name }}'
          title: '[ci] Release ${{ github.ref_name }}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger validate-remote-assets
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'validate-remote-assets.yml',
              ref: 'main',
              inputs: {
                pullRequestNumber: `${{steps.create_release_pr.outputs.pullRequestNumber}}`
              }
            })

      # Compressed size action doesn't support workflow_dispatch
      - name: Trigger codeQL, coveralls, e2e, unit-tests
        uses: actions/github-script@v6
        with:
          script: |
            const workflows = ["codeql-analysis.yml", "coveralls.yml", "e2e.yml", "unit-tests.yml"];
            workflows.forEach(workflow => github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: workflow,
              ref: "main"
            }))