name: Release

on:
  push:
    branches:
      - ci/use_reusable_workflows

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  test:
    # Prevents changesets action from creating a PR on forks
    if: github.repository == 'adyen/adyen-web'
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.15

      - name: Install Dependencies
        run: yarn

  call-coverall:
    uses: ./.github/workflows/coveralls.yml